/**
 * Weapon API
 * Move your app forward with the Weapon API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Parameter from './Parameter';





/**
* The Node model module.
* @module model/Node
* @version 1.0.0
*/
export default class Node {
    /**
    * Constructs a new <code>Node</code>.
    * @alias module:model/Node
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Node</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Node} obj Optional instance to populate.
    * @return {module:model/Node} The populated <code>Node</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Node();

            
            
            

            if (data.hasOwnProperty('nodeName')) {
                obj['nodeName'] = ApiClient.convertToType(data['nodeName'], 'String');
            }
            if (data.hasOwnProperty('parameters')) {
                obj['parameters'] = ApiClient.convertToType(data['parameters'], [Parameter]);
            }
        }
        return obj;
    }

    /**
    * Node Name.
    * @member {String} nodeName
    */
    nodeName = undefined;
    /**
    * Parameters list.
    * @member {Array.<module:model/Parameter>} parameters
    */
    parameters = undefined;








}


