/**
 * Weapon API
 * Move your app forward with the Weapon API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Parameter model module.
* @module model/Parameter
* @version 1.0.0
*/
export default class Parameter {
    /**
    * Constructs a new <code>Parameter</code>.
    * @alias module:model/Parameter
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Parameter</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Parameter} obj Optional instance to populate.
    * @return {module:model/Parameter} The populated <code>Parameter</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Parameter();

            
            
            

            if (data.hasOwnProperty('keyName')) {
                obj['keyName'] = ApiClient.convertToType(data['keyName'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
    * Key Name.
    * @member {String} keyName
    */
    keyName = undefined;
    /**
    * Key value.
    * @member {String} value
    */
    value = undefined;








}


