/**
 * Weapon API
 * Move your app forward with the Weapon API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Project model module.
* @module model/Project
* @version 1.0.0
*/
export default class Project {
    /**
    * Constructs a new <code>Project</code>.
    * @alias module:model/Project
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Project</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Project} obj Optional instance to populate.
    * @return {module:model/Project} The populated <code>Project</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Project();

            
            
            

            if (data.hasOwnProperty('projectName')) {
                obj['projectName'] = ApiClient.convertToType(data['projectName'], 'String');
            }
            if (data.hasOwnProperty('nodes')) {
                obj['nodes'] = ApiClient.convertToType(data['nodes'], 'String');
            }
        }
        return obj;
    }

    /**
    * Unique identifier.
    * @member {String} projectName
    */
    projectName = undefined;
    /**
    * Username of user.
    * @member {String} nodes
    */
    nodes = undefined;








}


